### ISSUE TITLE
Break out into separate projects?

### ISSUE THREAD

**Issue by lazerwalker** [ibgib/ask-gib#29]
Hi!

First of all, thanks so much for making this. Everything in this project looks phenomenal!

Question for you: I'm working on adding TS definitions to a library that's essentially an abstraction on top of the regular ASK SDK (http://github.com/alexa-js/alexa-app). That library naturally exposes some of the raw JSON objects returned by Alexa, which means that adding in my own type definitions is naturally leading me down the rabbithole of having to write definitions for e.g. the various JSON interface objects.

I'd love to build on your work, since you've already got awesome up-to-date type files for all of those. However, right now my options are either copying/pasting the files I need (with full attribution / adding license headers to each file / etc, obviously!) or pulling in this whole library as a dependency, which includes a whole bunch of functionality and code I don't need.

Would you be at all amenable to splitting this project out into smaller separate modules/packages that each just expose one bit of functionality? I'd love to e.g. `npm install askGib/types`. Presumably, there could still be a master `askGib` repo that includes all of those packages in a singular package like exists now.

Happy to help out however I can, but naturally the nature of that work means there'd still sadly be a bunch of responsibility placed on you to have a whole bunch more repos under your account / claim ownership of a bunch of new npm modules / etc.

**Comment by bill-mybiz** [comment]
@lazerwalker Howdy!

Thanks for the compliments. I'm still chugging away at this thing and it's good to hear that someone else finds it useful.

I'm not quite sure what exactly you're looking for? I'm certainly amenable to pulling out type definitions if that is what you're asking about?  I haven't done that as the last time I looked, there were [already definitions on DT](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/alexa-sdk) and I wasn't a fan of how they were done. 

> Would you be at all amenable to splitting this project out into smaller separate modules/packages that each just expose one bit of functionality? I'd love to e.g. npm install askGib/types. Presumably, there could still be a master askGib repo that includes all of those packages in a singular package like exists now.

I've considered splitting up the whole package into multiple packages like:

* Skill/Core
  * With base `AlexaSkill` and easier/more functional [`FuncyAlexaSkill`](https://github.com/ibgib/askGib/blob/master/src/funcy-alexa-skill.ts)
  * Would include the core type definitions located in [`alexa-skills-kit.ts`](https://github.com/ibgib/askGib/blob/master/src/alexa-skills-kit.ts)
* [`Ssml`](https://github.com/ibgib/askGib/blob/master/src/ssml.ts) helper
  * Which I see is similar to [ssml-builder](https://github.com/mandnyc/ssml-builder), but I prefer my TS! :laughing: 
* [`Lex`](https://github.com/ibgib/askGib/blob/master/src/lex.ts)
  * Alternative-driven data which is making the dynamic interaction much easier to work with for me personally.

But I think what you're looking for are only the type definitions located in `alexa-skills-kit.ts`?

I think if you tell me exactly which pieces you're looking for I can try to make it happen. If not, then I am not too concerned about attribution or anything on your part (but that's cool if ya do). Worst case is you can watch the changes here and manually update  (:scream:).

**Comment by bill-mybiz** [comment]
Oh, also, do you happen to know if the regular alexa-app repo you linked to is the newer version of https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs (which was itself a newer version of a previously deprecated repo)? Things keep changing so fast - I'm too old to keep up!

**Comment by bill-mybiz** [comment]
@lazerwalker I've just re-read your question after some hammock time, and I realized that you already answered my question about something specific. Apologies, I'm a slow thinker nowadays...

Yes, I can pull out those types in the `alexa-skill-kit.ts` file into their own repo, or hopefully get something up on Definitely Typed. Then you should just be able to install the types alone with something like `npm install @types/aws-gib`. If I can't figure out how to publish to DT, then I'll just create another repo/package with only those types. 

Like I said, I've been meaning to do something like this anyway, and this is a good motivator :+1:

**Comment by bill-mybiz** [comment]
Well, I've created something. I've put the types and constants into its own package called ask-gib-api. The npm page is [here](https://www.npmjs.com/package/ask-gib-api).

I went ahead with its own package, because the string literal enums that I use actually build constants and so it's not just `interface` declarations. I think that means it's not really a DT package, but meh. Check it out and let me know if that works for you. Tomorrow, I'm going to see if it works for me with askGib.

I also might go ahead and break out `Ssml` and `Lex` into their own packages as well. We'll see what happens. :wink:

**Comment by bill-mybiz** [comment]
Ok, my brain is a bit mush right now. All broken out. Let me know if that helps. :sweat_smile: 

* https://www.npmjs.com/package/ask-gib-api
* https://www.npmjs.com/package/lex-gib
* https://www.npmjs.com/package/ssml-gib
* https://www.npmjs.com/package/helper-gib

**Comment by bill-mybiz** [comment]
Stuff is broken...out. Closing now. Will reopen if new breakings required. :broken_heart:

**Comment by lazerwalker** [comment]
Ack, sorry to drop in the issue and disappear :)

That's absolutely perfect — grabbing `ask-gib-api` for my project now.

Thanks so much!

**Comment by bill-mybiz** [comment]
Awesome!  You're very welcome and thanks again for taking the time to open this issue. Did wonders for my motivation on this goal. 😃
